language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: v97M7qMN7jQHNv7cn394btJaPF6uKsBXA6QsfB7CKYCRdtA7aRY2y7OGzlSzQn94BfTLc/cJQbCMvjmLFwHYiV8Zw5HpzxvEwdf1+vhaEyswYO8SFO28XQV/RYic2+Ir18DMzf1w592Oeo5s4cci9fnpYYlefh+c2W1yJW9d2zCZ+qzfKUFRRTSQqK1SNPsJsMsyaqFVhSgJwmDS6YGHGjKc8ClZE14Bf1FtB3cxlGUhnBGAW9Qdj+yIX8PDTiR9XHxwcE0EtEQYUidJXOLBir0qXRbnJDcY30hY+LK2om2Q/8ur4FOCaqvgjlZcvIeVQKES0QOc2OsASQXI/p4RnJvgqo2o8hEH4xJII9/pOfIlaGtZxR0XRMxe4rCFlDhwa4F5+p6ZDRYn67oqs5Xw79taYEm9L/EdmgggWNfkzLV5MVN2xwfNv9zGSyFDCunfbQKajLDCYIV5jcdnLYQPEOpBTmPJyZbCKHPPyb4sexsan6wdQYGf3pry/CVpi/6WwXQEiwdghQG1wX23JX92A/wsJ00f6KYd7hoeT5F98sFUyZAqoKVYbshOeAmwHjnzJDph6YBBQ7XhCKx5jVfUULcgfrXeDXg6Xn5s9ko4TM136A4pgk1JSOMV978cDSkqU3iTIHhYOxhOnhAybH5yS+KM2O1LKsPeww28TNhYpwU=
  app: blog-api-challenge
  on:
    repo: aleyesa/blog-api-challenge
